### ISSUE TITLE
Unify handling of security policy and hashbuilding

### ISSUE THREAD

**Issue by mkv-vcm** [vacuumlabs/ledger-app-cardano-shelley#118]
In the different APDU steps it's kind of random now what the order is.

**Comment by janmazak** [comment]
We are talking about
1. determining security policy
2. checking if the policy is not DENY
3. applying security policy to UI
4. calling tx hash builder
5. possibly some other stuff (that comes after parsing APDU data)

**Comment by janmazak** [comment]
Fixed in #148.
