### ISSUE TITLE
pool_vk display in the ledger gui during an opcert generation/renewal

### ISSUE THREAD

**Issue by gitmachtl** [vacuumlabs/ledger-app-cardano-shelley#171]
EDIT: The used prefix of "pool_vk" is wrong, a simple change to "pool" should fix it.

### versions used
- ledger-app-cardano-shelley 5.0.0 - commit [b33a914](https://github.com/vacuumlabs/ledger-app-cardano-shelley/commit/b33a91409d6dcef51084804c5530d687f91d7b6e)
- cardano-hw-cli 1.11.0-rc2 - commit [1bef514](https://github.com/vacuumlabs/cardano-hw-cli/commit/1bef514e36f89fa353b36c1f052fcef44b17accf)
- cardano-node 1.35.3-rc1 - commit [950c4e2](https://github.com/input-output-hk/cardano-node/commit/950c4e222086fed5ca53564e642434ce9307b0b9)
- cardano-cli 1.35.3-rc1 - commit [950c4e2](https://github.com/input-output-hk/cardano-node/commit/950c4e222086fed5ca53564e642434ce9307b0b9)

### problem
During the opcert generation or renewal via a ledger device, the gui shows a pool id like
`pool_vk1tqs9gax7phvsdkhq9ceu44zmkf9zruddu6h4w3tmd6shrxz5ztxnt5qce08rf`
which is first, an uncommon representation of a pool id with a leading `pool_vk`, but more important it does not match anything in the cold.vkey file of the pool.

The bech pool-id used is the bech representation is the blake hash of the bytearray part from the .cborHex in the cold.vkey (publicKey) without the cbor identifier `5820`. The displayed `pool_vk...` representation does not match the bech converted part of only the bytearray. So i guess this representation is just wrong, or do i miss something here?

The next item that is displayed during the opcert generation is the bytearray bech part of the KES vkey in the format like
`kes_vk104k36mgy2ph0qcq20urp5hmervemfne7t5e780a6axwfgjr8xpwqv4tkwl`
that is correct KES.vkey file.

**Comment by janmazak** [comment]
@gitmachtl The correct prefix for pool id should be just `pool`, right? (According to CIP-5.)

**Comment by gitmachtl** [comment]
> @gitmachtl The correct prefix for pool id should be just `pool`, right? (According to CIP-5.)

yes.

was not sure if its a app or a hw-cli issue, because the app can derive the public key too, so was not sure.

**Comment by gitmachtl** [comment]
@janmazak got it... the calculation is correct, its just the wrong prefix. i tried building a pool-id with prefix "pool_vk" and that matched the displayed id. so, just remove the "_vk" when building the id and all good! 👍

**Comment by gitmachtl** [comment]
fixed with https://github.com/vacuumlabs/ledger-app-cardano-shelley/pull/162/commits/74a2efd745b1e9b235a04fd528466d3dfd8aeaab
