### ISSUE TITLE
Wrong checksum in `pool1…` Bech32 address during stake delegation

### ISSUE THREAD

**Issue by HeptaSean** [vacuumlabs/ledger-app-cardano-shelley#216]
When trying to delegate to a stake pool, the `pool1…` Bech32 address displayed on the Ledger has the wrong checksum, the wrong last six characters:
![screenshot-2024-04-21-17:17:19](https://github.com/vacuumlabs/ledger-app-cardano-shelley/assets/1820735/e37d0266-daff-43e0-8c4a-08ae67ca6f9b)
![IMG_20240421_171324](https://github.com/vacuumlabs/ledger-app-cardano-shelley/assets/1820735/f0fdccad-dd9e-473e-b7d4-e64735ce11ff)
![IMG_20240421_171338](https://github.com/vacuumlabs/ledger-app-cardano-shelley/assets/1820735/5154cd3a-7bc6-4df3-a384-30bdb136917e)

I think I have tracked down the issue to https://github.com/vacuumlabs/ledger-app-cardano-shelley/blob/develop/src/signTx_ui.c#L391-L403 where the second argument to `ui_displayBech32Screen` is `"to pool"`, but the second argument is supposed to be the Bech32 human-readable prefix according to https://github.com/vacuumlabs/ledger-app-cardano-shelley/blob/develop/src/uiScreens_bagl.c#L40-L74, which would be just `"pool"`. This explains the wrong checksum.

**Comment by HeptaSean** [comment]
For what it's worth: Bug was introduced with https://github.com/vacuumlabs/ledger-app-cardano-shelley/commit/cbf2812de2a05ddefb6329f1cc19c11db1e83b46.

**Comment by janmazak** [comment]
Thanks for the report, we'll fix that.

**Comment by janmazak** [comment]
Fixed in https://github.com/vacuumlabs/ledger-app-cardano-shelley/pull/211/commits/6f20e60c13c26f11bc0dcf4811d0d99de894c9a8, will be released in v7.1.1 (presumably on 25th June).
