### ISSUE TITLE
Enforce canonical ordering of entries serialized as maps

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/ledger-app-cardano-shelley#62]
Related ledgerjs issue with more context: https://github.com/vacuumlabs/ledgerjs-cardano-shelley/issues/95

This applies to tokenBundle and withdrawals as both are serialized in the tx body as maps, see https://github.com/input-output-hk/cardano-ledger-specs/blob/d99dcda8c06a1bad301ebd4cad56cf51ab03852d/shelley-ma/shelley-ma-test/cddl-files/shelley-ma.cddl#L24

Solution proposed:
* while consuming withdrawals/assets of the token bundle, keep in state the last processed entry and compare the next one against it, verifying that they are passed in a strictly ascending order (i.e. canonical ordering without repetition of keys)

**Comment by janmazak** [comment]
Resolved in #98.
