### ISSUE TITLE
Make certain security features customizable for better UX

### ISSUE THREAD

**Issue by refi93** [vacuumlabs/ledger-app-cardano-shelley#83]
Starting this issue to collect pain-points related to Ledger integration with wallets and act on them:

1. public key export call always triggers a prompt on the device. This is a complication for BIP44 wallets like Adalite where a sequential account discovery requires loading one public key at a time and bulk export prompts to eager load multiple keys result in unintuitive UI and complex caching/eager loading logic.

2. Some wallets may use withdrawals as replacements for unspent outputs in which case prompting the user to confirm them may result in an unintuitive UX for them (TBD though it is desired from an accounting perspective as staking rewards may have a different tax burden than the standard "capital gains")

**Comment by janmazak** [comment]
Mostly resolved, also by introducing expert mode.
