### ISSUE TITLE
Remove unnecessary validation checks

### ISSUE THREAD

**Issue by KubqoA** [vacuumlabs/ledger-app-cardano-shelley#91]
For security, it is better to check everything twice than risk not checking at all, but since we have problem with total code size, it seems preferable to drop checks that are obviously superfluous and just rely on the functions reading the view. Identify all situations like this:
```
		VALIDATE(view_remainingSize(view) >= 4, ERR_INVALID_DATA);
		params->protocolMagic = parse_u4be(view);
```
and remove the validation.

**Comment by janmazak** [comment]
Done in #98
