### ISSUE TITLE
consider unifying enum constant names with ledgerjs

### ISSUE THREAD

**Issue by janmazak** [vacuumlabs/ledger-app-cardano-shelley#93]
Our terminology is not consistent between C and JS code. For instance, KEY_REFERENCE_PATH vs. DEVICE_OWNED in certain enums. 

We have already unified on "singing mode" instead of "usecase", but it is preferable to use the same terms everywhere.

**Comment by mkv-vcm** [comment]
Couldn't find significant discrepancies.
